server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.czd5bsi7h6n9.ap-northeast-2.rds.amazonaws.com/mspracdb?autoReconnect=true # 변경해주세요
    #url: jdbc:mysql://localhost:3306/beamintestdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1217resart!!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전